ecovery/src/main/java/com/ecovery/constant/ItemSellStatus.java
ecovery/src/main/java/com/ecovery/constant/OrderStatus.java
ecovery/src/main/java/com/ecovery/constant/PayStatus.java
ecovery/src/main/java/com/ecovery/domain/CartItemVO.java
ecovery/src/main/java/com/ecovery/domain/CartVO.java
ecovery/src/main/java/com/ecovery/domain/ItemImgVO.java
ecovery/src/main/java/com/ecovery/domain/ItemVO.java
ecovery/src/main/java/com/ecovery/domain/OrderItemVO.java
ecovery/src/main/java/com/ecovery/domain/OrderVO.java
ecovery/src/main/java/com/ecovery/domain/PaymentVO.java
ecovery/src/main/java/com/ecovery/domain/PointVO.java
ecovery/src/main/java/com/ecovery/dto/ItemDto.java
ecovery/src/main/java/com/ecovery/dto/ItemImgDto.java
ecovery/src/main/java/com/ecovery/dto/OrderDto.java
ecovery/src/main/java/com/ecovery/mapper/ItemMapper.java

주문, 상품, 결제, 포인트, 장바구니 VO 생성 완료하였습니다.
DTO는 Item, ItemImg, Order만 생성하였습니다.
ItemMapper는 아직 코드 작성 전입니다.

에코마켓 상세 페이지 VO, DTO, Mapper

---

.idea/.name
.idea/modules.xml
.idea/modules/ecovery.main.iml
.idea/modules/ecovery.test.iml
.idea/vcs.xml
ecovery/src/main/java/com/ecovery/domain/FreeImgVO.java
ecovery/src/main/java/com/ecovery/domain/FreeReplyVO.java
ecovery/src/main/java/com/ecovery/domain/FreeVO.java
ecovery/src/main/java/com/ecovery/dto/Criteria.java
ecovery/src/main/java/com/ecovery/dto/FreeDTO.java
ecovery/src/main/java/com/ecovery/dto/FreeImgDTO.java
ecovery/src/main/java/com/ecovery/dto/FreeReplyDTO.java
ecovery/src/main/java/com/ecovery/dto/PageDTO.java
ecovery/src/main/java/com/ecovery/mapper/FreeImgMapper.java
ecovery/src/main/java/com/ecovery/mapper/FreeMapper.java
free.sql

2025-07-10 (목)
1. 무료나눔 게시글 댓글 테이블 네임 reply -> free_reply로 변경
-> 통일성을 주기위해 .. 직관적으로 변경했습니다. 
2.  FreeDto, FreeImgDto, FreeReplyDto 생성 
-> FreeDto에서 날짜 타입 String으로  지정 
3.  Criteria, PageDto => dto 폴더 안에 생성
-> criteria는 DB에 존재하는 테이블이 아니고, 화면/요청을 위한 데이터 전달 객체라서  DTO 역할을 하기 때문에 dto 폴더 안에 넣었음 
4. Mapper는 진행중 ...

무료나눔 Dto 클래스 완료

---

.idea/.name
.idea/vcs.xml
ecovery/build.gradle
ecovery/src/main/java/com/ecovery/config/SecurityConfig.java
ecovery/src/main/java/com/ecovery/controller/MemberController.java
ecovery/src/main/java/com/ecovery/domain/MemberVO.java
ecovery/src/main/java/com/ecovery/mapper/MemberMapper.java
ecovery/src/main/java/com/ecovery/security/CustomUserDetails.java
ecovery/src/main/java/com/ecovery/security/CustomUserDetailsService.java
ecovery/src/main/java/com/ecovery/service/MemberService.java
ecovery/src/main/java/com/ecovery/service/MemberServiceImpl.java
ecovery/src/main/resources/mapper/MemberMapper.xml

Member 작성 완료, 시큐리티 폴더 생성하여 작성 완료, 정상적으로 중복 확인 되는지 내일 확인 예정

login 기능 구현중

---

.idea/vcs.xml

깃 올리기 테스트 입니다

---

DB 2차 정리.txt
ecovery/src/main/java/com/ecovery/controller/ItemController.java
ecovery/src/main/java/com/ecovery/domain/ItemVO.java
ecovery/src/main/java/com/ecovery/dto/ItemDto.java
ecovery/src/main/java/com/ecovery/dto/ItemFormDto.java
ecovery/src/main/java/com/ecovery/service/ItemImgServiceImpl.java
ecovery/src/main/resources/application.yml
ecovery/src/main/resources/templates/item/itemDtl.html

에코마켓 상세 페이지의 ItemService, ItemImgService, ItemController, ItemDtl (상세 페이지) 구현했습니다.

에코마켓 상세 페이지_Service, Controller

---

.idea/Ecovery.iml
.idea/modules.xml
.idea/modules/ecovery.main.iml
.idea/modules/ecovery.test.iml
ecovery/src/main/java/com/ecovery/dto/Criteria.java
ecovery/src/main/resources/mapper/EnvMapper.xml
ecovery/src/test/java/com/ecovery/mapper/EnvMapperTest.java

[EnvMapper.xml] 게시글 등록, 삭제, 수정 기능 추가
[EnvMapperTest] 게시글 등록, 삭제, 수정 테스트 작성
[Criteria] getOffset() 추가

EnvMapper 수정까지 테스트 완료

---

.idea/vcs.xml
ecovery/src/main/java/com/ecovery/domain/DisposalFeedbackVO.java
ecovery/src/main/java/com/ecovery/domain/DisposalHistoryImgVO.java
ecovery/src/main/java/com/ecovery/domain/DisposalHistoryVO.java
ecovery/src/main/java/com/ecovery/mapper/DisposalFeedbackMapper.java
ecovery/src/main/java/com/ecovery/mapper/DisposalHistoryImgMapper.java
ecovery/src/main/java/com/ecovery/mapper/DisposalHistoryMapper.java
ecovery/src/main/java/com/ecovery/service/DisposalFeedbackService.java
ecovery/src/main/java/com/ecovery/service/DisposalFeedbackServiceImpl.java
ecovery/src/main/java/com/ecovery/service/DisposalHistoryImgService.java
ecovery/src/main/java/com/ecovery/service/DisposalHistoryImgServiceImpl.java
ecovery/src/main/java/com/ecovery/service/DisposalHistoryService.java
ecovery/src/main/java/com/ecovery/service/DisposalHistoryServiceImpl.java
ecovery/src/main/resources/mapper/DisposalFeedbackMapper.xml
ecovery/src/main/resources/mapper/DisposalHistoryImgMapper.xml
ecovery/src/main/resources/mapper/DisposalHistoryMapper.xml

disposal 관련 mapper 완성.
historymapper에 join 사용.
service 간단하게 작성.

disposal 서비스 코드 작성

---

.idea/modules.xml
.idea/modules/ecovery.main.iml
ecovery/src/main/java/com/ecovery/service/EnvService.java
ecovery/src/main/java/com/ecovery/service/EnvServiceImpl.java
ecovery/src/main/resources/application.yml
ecovery/src/main/resources/mapper/EnvMapper.xml
ecovery/src/test/java/com/ecovery/service/EnvServiceTest.java

[EnvService]EnvService 인터페이스 최초 작성 (CRUD, 페이징)
[EnvServiceImpl]EnvServiceImpl 클래스 최초 작성 (CRUD 구현)
[EnvMapper.xml]게시글 목록 조회 (페이징 + 검색) 기능 추가
[application.yml]이미지 경로 수정 (shop -> ecovery)
[EnvServiceTest]게시글 등록, 단건 조회, 수정, 삭제 테스트 작성

[20250715]EnvService CRUD까지 완료

---

.idea/modules/ecovery.main.iml
.idea/vcs.xml
ecovery/src/main/java/com/ecovery/controller/DisposalFeedbackController.java
ecovery/src/main/java/com/ecovery/controller/DisposalHistoryController.java
ecovery/src/main/java/com/ecovery/domain/DisposalHistoryVO.java
ecovery/src/main/java/com/ecovery/dto/DisposalFeedbackDto.java
ecovery/src/main/java/com/ecovery/dto/DisposalHistoryDto.java
ecovery/src/main/java/com/ecovery/dto/DisposalHistoryImgDto.java
ecovery/src/main/java/com/ecovery/mapper/DisposalFeedbackMapper.java
ecovery/src/main/java/com/ecovery/mapper/DisposalHistoryImgMapper.java
ecovery/src/main/java/com/ecovery/mapper/DisposalHistoryMapper.java
ecovery/src/main/java/com/ecovery/service/DisposalFeedbackService.java
ecovery/src/main/java/com/ecovery/service/DisposalFeedbackServiceImpl.java
ecovery/src/main/java/com/ecovery/service/DisposalHistoryImgService.java
ecovery/src/main/java/com/ecovery/service/DisposalHistoryImgServiceImpl.java
ecovery/src/main/java/com/ecovery/service/DisposalHistoryService.java
ecovery/src/main/java/com/ecovery/service/DisposalHistoryServiceImpl.java
ecovery/src/main/resources/mapper/DisposalFeedbackMapper.xml
ecovery/src/main/resources/mapper/DisposalHistoryMapper.xml

이미지 관련 코드 보완해야함

---

.idea/sqldialects.xml
ecovery/src/main/java/com/ecovery/config/SecurityConfig.java
ecovery/src/main/java/com/ecovery/controller/EnvController.java
ecovery/src/main/java/com/ecovery/mapper/EnvMapper.java
ecovery/src/main/java/com/ecovery/service/EnvService.java
ecovery/src/main/java/com/ecovery/service/EnvServiceImpl.java
ecovery/src/main/resources/mapper/EnvMapper.xml
ecovery/src/main/resources/templates/env/list.html
ecovery/src/test/java/com/ecovery/mapper/EnvMapperTest.java
ecovery/src/test/java/com/ecovery/service/EnvServiceTest.java

[EnvMapper]조회수 증가 추가
[EnvMapper.xml]게시글 목록 조회 (페이징 + 검색) 코드 수정, 전체 게시글 개수 조회, 게시글 조회수 증가 기능 추가
[EnvMapperTest]게시글 페이징 + 검색 목록 조회, 전체 게시글 개수 조회, 조회수 증가 테스트 작성
[EnvService]조회수 증가 추가
[EnvServiceImpl]게시글 목록 조회 (페이징 포함), 게시글 총 개수 조회, 조회수 증가 추가
[EnvServiceTest]게시글 목록 조회 (페이징 포함), 게시글 총 개수 조회, 조회수 증가 테스트 작성
[EnvController]EnvController 클래스 최초 작성 (목록 조회)
[list.html]EnvController의 목록 조회 기능을 확인하기 위해 임시로 만든 파일
[SecurityConfig]환경톡톡 게시판 누구나 접근 가능하게 변경

[20250716]환경톡톡 서비스테스트까지 완료

---

.idea/modules.xml
DB 2차 정리.txt
ecovery/src/main/java/com/ecovery/config/WebMvcConfig.java
ecovery/src/main/java/com/ecovery/controller/ItemController.java
ecovery/src/main/java/com/ecovery/domain/ItemVO.java
ecovery/src/main/java/com/ecovery/dto/ItemFormDto.java
ecovery/src/main/java/com/ecovery/dto/ItemImgDto.java
ecovery/src/main/java/com/ecovery/mapper/ItemImgMapper.java
ecovery/src/main/java/com/ecovery/mapper/ItemMapper.java
ecovery/src/main/java/com/ecovery/service/ItemImgService.java
ecovery/src/main/java/com/ecovery/service/ItemImgServiceImpl.java
ecovery/src/main/java/com/ecovery/service/ItemService.java
ecovery/src/main/java/com/ecovery/service/ItemServiceImpl.java
ecovery/src/main/resources/application.yml
ecovery/src/main/resources/mapper/ItemImgMapper.xml
ecovery/src/main/resources/mapper/ItemMapper.xml
ecovery/src/main/resources/templates/item/itemForm.html
ecovery/src/main/resources/templates/item/itemList.html
ecovery/src/test/java/com/ecovery/mapper/ItemImgMapperTest.java
ecovery/src/test/java/com/ecovery/mapper/ItemMapperTest.java

에코마켓 등록 구현 완료

---

DB 2차 정리.txt
ecovery/src/main/java/com/ecovery/controller/ItemController.java
ecovery/src/main/java/com/ecovery/domain/ItemVO.java
ecovery/src/main/java/com/ecovery/dto/CategoryDto.java
ecovery/src/main/java/com/ecovery/dto/ItemDto.java
ecovery/src/main/java/com/ecovery/dto/ItemFormDto.java
ecovery/src/main/java/com/ecovery/mapper/CategoryMapper.java
ecovery/src/main/java/com/ecovery/mapper/ItemImgMapper.java
ecovery/src/main/java/com/ecovery/mapper/ItemMapper.java
ecovery/src/main/java/com/ecovery/service/CategoryService.java
ecovery/src/main/java/com/ecovery/service/CategoryServiceImpl.java
ecovery/src/main/java/com/ecovery/service/ItemImgService.java
ecovery/src/main/java/com/ecovery/service/ItemImgServiceImpl.java
ecovery/src/main/java/com/ecovery/service/ItemService.java
ecovery/src/main/java/com/ecovery/service/ItemServiceImpl.java
ecovery/src/main/resources/mapper/CategoryMapper.xml
ecovery/src/main/resources/mapper/ItemImgMapper.xml
ecovery/src/main/resources/mapper/ItemMapper.xml
ecovery/src/main/resources/templates/item/List.html
ecovery/src/main/resources/templates/item/itemList.html
ecovery/src/test/java/com/ecovery/mapper/CategoryMapperTest.java
ecovery/src/test/java/com/ecovery/mapper/ItemImgMapperTest.java
ecovery/src/test/java/com/ecovery/mapper/ItemMapperTest.java
ecovery/src/test/java/com/ecovery/service/ItemServiceTest.java

에코마켓 수정, 삭제 구현 완료했습니다.
아직 View 연결 확인 전입니다.

에코마켓 수정, 삭제 구현 완료

---

ecovery/src/main/java/com/ecovery/controller/ItemController.java
ecovery/src/main/java/com/ecovery/service/ItemServiceImpl.java
ecovery/src/main/resources/mapper/CategoryMapper.xml
ecovery/src/main/resources/templates/item/List.html

ecomarket_중간 점검

---

ecovery/src/main/java/com/ecovery/config/SecurityConfig.java
ecovery/src/main/java/com/ecovery/controller/FreeController.java
ecovery/src/main/java/com/ecovery/controller/FreeRestController.java
ecovery/src/main/java/com/ecovery/dto/FreeDto.java
ecovery/src/main/java/com/ecovery/mapper/FreeImgMapper.java
ecovery/src/main/java/com/ecovery/mapper/FreeMapper.java
ecovery/src/main/java/com/ecovery/service/FreeImgService.java
ecovery/src/main/java/com/ecovery/service/FreeImgServiceImpl.java
ecovery/src/main/java/com/ecovery/service/FreeServiceImpl.java
ecovery/src/main/resources/application.yml
ecovery/src/main/resources/mapper/FreeImgMapper.xml
ecovery/src/main/resources/mapper/FreeMapper.xml
ecovery/src/main/resources/templates/free/list.html
ecovery/src/test/java/com/ecovery/controller/FreeControllerTest.java
ecovery/src/test/java/com/ecovery/mapper/FreeImgMapperTest.java
ecovery/src/test/java/com/ecovery/mapper/FreeMapperTest.java
ecovery/src/test/java/com/ecovery/service/FreeImgServiceTest.java
ecovery/src/test/java/com/ecovery/service/FreeServiceTest.java

2025-07-21 (월) service1-yeonsu
1. FreeServiceTest 완성 
- FreeImgService 주입 
2. FreeImgService, FreeImgServiceImpl 작성 
- application.yml 파일에서 무료나눔 게시판 이미지 저장 경로 추가 
-> freeImgLocation: C:/ecovery/free
- 대표이미지 한장 조회하는 코드 제거 
-> 리스트 화면에서 대표 이미지 나오게 하려했는데 그냥 ,, xml에서 y인지 체크하는걸로 코드 바꿈
3. category 테이블 생성 후 FreeMapper.xml에 join코드 추가 
FreeDto에도 category 필드 추가했음..
4. 게시글 삭제시 작성자랑 관리자 둘 다 가능하게 하기위해서 
dto에 memberId 추가하고 mapper, service, controller 다 수정했음 
5. FreeController 완성..! FreeControllerTest... 진행..
- FreeController에 권한 설정해서 작성함 
(게시글 목록 : 누구나, 게시글 등록 : 회원, 게시글 수정 : 작성자, 게시글 삭제 : 관리자 OR 작성자)

FreeController-ing..

---

ecovery/src/main/java/com/ecovery/controller/CartController.java
ecovery/src/main/java/com/ecovery/controller/MemberController.java
ecovery/src/main/java/com/ecovery/mapper/CartItemMapper.java
ecovery/src/main/java/com/ecovery/mapper/CartMapper.java
ecovery/src/main/java/com/ecovery/mapper/OrderMapper.java
ecovery/src/main/java/com/ecovery/service/CartItemItemServiceImpl.java
ecovery/src/main/java/com/ecovery/service/CartItemService.java
ecovery/src/main/java/com/ecovery/service/CartService.java
ecovery/src/main/java/com/ecovery/service/CartServiceImpl.java
ecovery/src/main/java/com/ecovery/service/MemberServiceImpl.java
ecovery/src/main/resources/mapper/CartItemMapper.xml
ecovery/src/main/resources/mapper/CartMapper.xml
ecovery/src/main/resources/static/js/eco-talk-script.js
ecovery/src/main/resources/static/js/mypage-script.js
ecovery/src/main/resources/static/js/script.js
ecovery/src/main/resources/static/js/write-post-script.js
ecovery/src/main/resources/templates/admin/admin.html
ecovery/src/main/resources/templates/cart/cart.html
ecovery/src/main/resources/templates/disposal/services.html
ecovery/src/main/resources/templates/disposal/waste-sorting.html
ecovery/src/main/resources/templates/env/register.html
ecovery/src/main/resources/templates/fragments/header.html
ecovery/src/main/resources/templates/item/List.html
ecovery/src/main/resources/templates/main.html
ecovery/src/main/resources/templates/member/signup.html
ecovery/src/main/resources/templates/mypage/mypage.html

장바구니 조회, 수정, 삭제 Mapper, Service, Controller 코드 기재 완료
구매이력 작성 중...

cart 조회 구현완료

---

disposal_info DB데이터.txt
ecovery/src/main/resources/static/css/services.css
ecovery/src/main/resources/static/js/services.js
ecovery/src/main/resources/templates/disposal/disposalMain.html

분리배출 2차 분류 모달창 가운데 정렬함.
송파구 이상함

2차분류 모달창 가운데 정렬

---

ecovery/src/main/java/com/ecovery/config/SecurityConfig.java
ecovery/src/main/java/com/ecovery/controller/ItemApiController.java
ecovery/src/main/java/com/ecovery/controller/OrderApiController.java
ecovery/src/main/java/com/ecovery/domain/OrderItemVO.java
ecovery/src/main/java/com/ecovery/domain/OrderVO.java
ecovery/src/main/java/com/ecovery/dto/OrderDto.java
ecovery/src/main/java/com/ecovery/dto/OrderItemDto.java
ecovery/src/main/java/com/ecovery/dto/OrderItemRequestDto.java
ecovery/src/main/java/com/ecovery/mapper/OrderMapper.java
ecovery/src/main/java/com/ecovery/service/ItemServiceImpl.java
ecovery/src/main/java/com/ecovery/service/OrderItemService.java
ecovery/src/main/java/com/ecovery/service/OrderItemServiceImpl.java
ecovery/src/main/java/com/ecovery/service/OrderService.java
ecovery/src/main/java/com/ecovery/service/OrderServiceImpl.java
ecovery/src/main/resources/mapper/ItemMapper.xml
ecovery/src/main/resources/mapper/OrderMapper.xml
ecovery/src/test/java/com/ecovery/controller/ItemApiControllerTest.java
ecovery/src/test/java/com/ecovery/mapper/ItemMapperTest.java
ecovery/src/test/java/com/ecovery/mapper/OrderMapperTest.java
ecovery/src/test/java/com/ecovery/service/ItemServiceTest.java
ecovery/src/test/java/com/ecovery/service/OrderItemServiceTest.java
ecovery/src/test/java/com/ecovery/service/OrderServiceTest.java

주문 페이지 요청, 주문 저장 Controller까지 작성 완료 (Test 미실행)

Order요청 Controller 구현 완료

---

ecovery/src/main/java/com/ecovery/controller/FreeApiController.java
ecovery/src/main/java/com/ecovery/dto/FreeReplyDto.java
ecovery/src/main/java/com/ecovery/mapper/FreeImgMapper.java
ecovery/src/main/java/com/ecovery/mapper/FreeReplyMapper.java
ecovery/src/main/java/com/ecovery/service/FreeImgService.java
ecovery/src/main/java/com/ecovery/service/FreeImgServiceImpl.java
ecovery/src/main/java/com/ecovery/service/FreeReplyService.java
ecovery/src/main/java/com/ecovery/service/FreeReplyServiceImpl.java
ecovery/src/main/resources/mapper/FreeImgMapper.xml
ecovery/src/main/resources/mapper/FreeReplyMapper.xml
ecovery/src/test/java/com/ecovery/controller/FreeControllerTest.java
ecovery/src/test/java/com/ecovery/mapper/FreeImgMapperTest.java
ecovery/src/test/java/com/ecovery/mapper/FreeReplyMapperTest.java
ecovery/src/test/java/com/ecovery/service/FreeImgServiceTest.java
ecovery/src/test/java/com/ecovery/service/OrderItemServiceTest.java
ecovery/src/test/java/com/ecovery/service/OrderServiceTest.java

2025-07-24 (목) controller1-yeonsu
1.FreeApiController 코드 및 주석까지 완료 
2. FreeControllertest 코드 및 주석까지 완료 
3. FreeImgVO, FreeImgDto, FreeImgMapper, FreeImgMapper.xml 최종 확인 후 
FreeImgMapperTest 코드 및 주석까지 완료 
4. FreeImgService, FreeImgServiceImpl, FreeImgServiceTest 코드작성완료 
5. FreeReplyMapper, FreeReplyMapper.xml, FreeReplyMapperTest 코드 및 주석까지 완료
FreeReplyService, FreeReplyServiceImpl, - 작성중,, 
-> 대댓글 수 조회는 빼기 ,, 안해도 될거 같음 ~!
<25일 금요일에 할 것>
FreeReplyServiceTest,
FreeReplyController, FreeReplyControllerTest 작성해야햄 ~!

FreeReplyService진행중

---

ecovery/build.gradle
ecovery/src/main/java/com/ecovery/controller/EnvApiController.java
ecovery/src/main/java/com/ecovery/controller/NoticeApiController.java
ecovery/src/main/java/com/ecovery/domain/MemberVO.java
ecovery/src/main/java/com/ecovery/mapper/MemberMapper.java
ecovery/src/main/java/com/ecovery/security/CustomUserDetails.java
ecovery/src/main/java/com/ecovery/service/OAuth2MemberService.java
ecovery/src/main/java/com/ecovery/service/OAuth2MemberServiceImpl.java
ecovery/src/main/resources/application.yml
ecovery/src/main/resources/mapper/MemberMapper.xml
ecovery/src/main/resources/static/js/notice-get.js
ecovery/src/main/resources/templates/fragments/header.html
ecovery/src/main/resources/templates/notice/get.html
ecovery/src/test/java/com/ecovery/controller/EnvApiControllerTest.java
ecovery/src/test/java/com/ecovery/controller/NoticeApiControllerTest.java
ecovery/src/test/java/com/ecovery/mapper/MemberMapperTest.java
ecovery/src/test/java/com/ecovery/service/OrderItemServiceTest.java
ecovery/src/test/java/com/ecovery/service/OrderServiceTest.java

[NoticeApiControllerTest]
공지사항 등록/수정/단건조회/삭제 실패 테스트 케이스 추가 (유효성 검증 및 존재하지 않는 ID)
[NoticeApiController]
게시글 삭제 실패 시 400 Bad Request 응답 처리
[EnvApiControlle]
게시글 삭제 실패 시 400 Bad Request 응답 처리
[EnvApiControllerTest]
공지사항 단건조회 성공, 등록/수정/단건조회/삭제 실패 테스트 케이스 추가 (유효성 검증 및 존재하지 않는 ID)
[카카오 디벨로퍼] 초기 설정 완료
[application.yml] 소셜 로그인 설정 추가
[DB]Member 테이블 컬럼 수정 & 추가
password : NULL 허용으로 변경 (소셜 사용자 비밀번호 없음)
provider : 로그인 방식 (local, kakao, google 등)
provider_id : 소셜 로그인 고유 ID (email이 없어도 식별 가능)
[MemberVO] 
소셜 로그인 필드(provider, providerId) 추가
[MemberMapper] 
소셜 로그인 사용자 조회 메서드 추가 (findBySocialId)
[MemberMapper.xml] 
소셜 로그인 조회 쿼리(findBySocialId), provider 관련 필드 및 insert 쿼리 추가
[MemberMapperTest]
소셜 로그인 회원 조회 테스트(findBySocialId) 작성
[build.gradle] 
OAuth2 클라이언트 기능을 제공하는 Spring Boot 의존성 추가
[OAuth2MemberService] …

[20250724] 소셜 로그인 서비스 중

---

ecovery/src/main/java/com/ecovery/domain/EnvImgVO.java
ecovery/src/main/java/com/ecovery/dto/EnvImgDto.java
ecovery/src/main/java/com/ecovery/mapper/EnvImgMapper.java
ecovery/src/main/java/com/ecovery/service/EnvImgService.java
ecovery/src/main/java/com/ecovery/service/EnvImgServiceImpl.java
ecovery/src/main/resources/application.yml
ecovery/src/main/resources/mapper/EnvImgMapper.xml
ecovery/src/test/java/com/ecovery/mapper/EnvImgMapperTest.java
ecovery/src/test/java/com/ecovery/service/EnvImgServiceTest.java

[DB] env_img 테이블 추가
CREATE TABLE env_img (
env_img_id BIGINT AUTO_INCREMENT PRIMARY KEY,
env_id BIGINT NOT NULL,
img_name VARCHAR(255) NOT NULL,
ori_img_name VARCHAR(255),
img_url VARCHAR(500) NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (env_id) REFERENCES env(env_id) ON DELETE CASCADE
);
[EnvImgVO]
환경톡톡 이미지 VO 클래스 최초 생성
[EnvImgDto]
환경톡톡 이미지 DTO 클래스 최초 생성
[EnvImgMapper]
이미지 등록, 조회, 삭제 메서드 정의
[EnvImgMapper.xml]
이미지 등록, 조회, 삭제 쿼리 작성
[EnvImgMapperTest]
이미지 등록, 조회, 삭제 단위 테스트 작성
[EnvImgService]
이미지 등록, 조회, 삭제 서비스 메서드 정의 (EnvImgDto 기반)
[EnvImgServiceImpl]
이미지 등록/조회/삭제 기능 구현
파일 저장 및 삭제 로직 추가
[application.yml]
환경톡톡 이미지 업로드 경로 추가
[EnvImgServiceTest]
이미지 등록, 목록 조회, 단일 삭제, 전체 삭제 테스트 작성중
[C:\ecovery\env] 폴더 만들기

[20250726] EnvImg 서비스 테스트 작성중

---

DB 2차 정리.txt
ecovery/src/main/java/com/ecovery/controller/MemberController.java

일반회원 회원가입 시 provider값 null값 나오는 오류 수정
[MemberController]
memberVO.setProvider("local");
memberVO.setProviderId(null);
코드 추가

[20250728] 일반회원 회원가입 오류 수정

---

ecovery/src/main/resources/static/js/memberList.js
ecovery/src/main/resources/templates/admin/memberList.html

멤버상세정보에 닉네임이 보이도록 수정

---

ecovery/src/main/java/com/ecovery/controller/ItemApiController.java
ecovery/src/main/java/com/ecovery/service/ItemServiceImpl.java
ecovery/src/main/resources/mapper/ItemImgMapper.xml
ecovery/src/main/resources/static/css/eco-market-detail.css
ecovery/src/main/resources/static/js/eco-market-detail-request.js
ecovery/src/main/resources/static/js/eco-market-detail.js
ecovery/src/main/resources/static/js/eco-market-register.js
ecovery/src/main/resources/templates/eco/eco-market-detail.html
ecovery/src/main/resources/templates/eco/eco-market-register.html

상세 페이지 기본 화면 구현 완료
세부 기능 추가 예정

상세 페이지 기본 화면 구현 완료

---

ecovery/src/main/resources/static/css/notice-detail.css
ecovery/src/main/resources/static/js/notice-detail.js
ecovery/src/main/resources/static/js/notice-get.js
ecovery/src/main/resources/static/js/notice-register.js
ecovery/src/main/resources/static/js/notice-write-script.js
ecovery/src/main/resources/templates/env/register.html
ecovery/src/main/resources/templates/main.html
ecovery/src/main/resources/templates/notice/get.html
ecovery/src/main/resources/templates/notice/list.html
ecovery/src/main/resources/templates/notice/register.html

1. 공지사항 상세보기 화면 만들기
notice/
[get.html]
[notice-get.js]
2. 공지사항 상세보기에서 헤드섹션 부분에 아이콘이 공지사항과 함께 있지 않고 위로 올라가 있는 오류
[get.html] 아이콘 부분은 <div> → <span>으로 변경, 아이콘과 문구를 또 div로 감싸기
[notice-detail.css] 코드 추가

[20250801] 공지사항 상세보기 페이지 완료

---

ecovery/src/main/java/com/ecovery/controller/AdminMainController.java
ecovery/src/main/java/com/ecovery/controller/ItemApiController.java
ecovery/src/main/java/com/ecovery/controller/ItemViewController.java
ecovery/src/main/java/com/ecovery/service/MemberServiceImpl.java
ecovery/src/main/resources/static/css/eco-market-edit.css
ecovery/src/main/resources/static/js/eco-market-edit.js
ecovery/src/main/resources/templates/admin/adminMain.html
ecovery/src/main/resources/templates/eco/eco-market-edit.html

에코마켓 수정페이지 작업 중

---

ecovery/src/main/java/com/ecovery/config/SecurityConfig.java
ecovery/src/main/java/com/ecovery/controller/CartController.java
ecovery/src/main/java/com/ecovery/controller/OrderViewController.java
ecovery/src/main/resources/static/css/eco-market-detail.css
ecovery/src/main/resources/static/js/eco-market-detail-request.js
ecovery/src/main/resources/static/js/eco-market-detail.js
ecovery/src/main/resources/static/js/eco-market-register.js
ecovery/src/main/resources/templates/eco/eco-market-detail.html
ecovery/src/main/resources/templates/eco/eco-market-register.html

상세 페이지 중간 점검용

---

DB 2차 정리.txt
ecovery/src/main/java/com/ecovery/controller/CartController.java
ecovery/src/main/java/com/ecovery/controller/OrderHistoryController.java
ecovery/src/main/java/com/ecovery/dto/OrderHistoryDto.java
ecovery/src/main/java/com/ecovery/service/CartItemServiceImpl.java
ecovery/src/main/resources/mapper/CartItemMapper.xml
ecovery/src/main/resources/mapper/OrderMapper.xml
ecovery/src/main/resources/static/js/cart-script.js
ecovery/src/main/resources/templates/cart/cart.html
ecovery/src/main/resources/templates/order/order-detail.html
ecovery/src/main/resources/templates/order/orderhistory.html
ecovery/src/test/java/com/ecovery/service/EnvImgServiceTest.java

장바구니, 주문조회 구현 완료
다음주 상세한 내용 구현 예정

장바구니, 주문조회 구현완료

---

.idea/modules.xml
.idea/modules/ecovery.test.iml
ecovery/src/main/java/com/ecovery/controller/ItemApiController.java
ecovery/src/main/java/com/ecovery/domain/ItemImgVO.java
ecovery/src/main/java/com/ecovery/dto/ItemImgDto.java
ecovery/src/main/java/com/ecovery/mapper/ItemImgMapper.java
ecovery/src/main/java/com/ecovery/service/FreeImgServiceImpl.java
ecovery/src/main/java/com/ecovery/service/ItemImgService.java
ecovery/src/main/java/com/ecovery/service/ItemImgServiceImpl.java
ecovery/src/main/java/com/ecovery/service/ItemService.java
ecovery/src/main/java/com/ecovery/service/ItemServiceImpl.java
ecovery/src/main/resources/mapper/ItemImgMapper.xml
ecovery/src/main/resources/static/css/eco-market-edit.css
ecovery/src/main/resources/static/js/eco-market-detail.js
ecovery/src/main/resources/static/js/eco-market-edit.js
ecovery/src/main/resources/templates/eco/eco-market-detail.html
ecovery/src/main/resources/templates/eco/eco-market-edit.html
ecovery/src/main/resources/templates/free/register.html

에코마켓 이미지 유지, 삭제, 추가 기능 구현 완료.
css 등은 손봐야 함

에코마켓 수정 페이지 기능 구현 완료

---

ecovery/src/main/java/com/ecovery/controller/OrderViewController.java
ecovery/src/main/resources/static/css/order-detail.css
ecovery/src/main/resources/templates/order/order-complete.html

주문 완료 페이지 만들기
[OrderViewController]
주문 완료 페이지 이동용 메서드 추가
@GetMapping("/complete/{orderId}")
[order-complete.html]
주문완료 페이지 수정
- 주문 정보/상품/배송/결제/버튼 섹션 구성
- order-detail.css 재사용 구조로 스타일 통일
- 주문 상태 텍스트 Thymeleaf로 조건 분기 처리
- 주문 상품 반복 렌더링 + 에러 시 SVG 대체 이미지 처리

[20250804] 주문완료 페이지 완료

---

ecovery/src/main/resources/static/css/eco-market-detail.css
ecovery/src/main/resources/static/js/eco-market-register.js
ecovery/src/main/resources/templates/eco/eco-market-detail.html

에코마켓 상세 페이지 HTML 수정, 상품 등록 알림 기능 수정 완료

에코마켓 부분 수정 완료

---

ecovery/src/main/java/com/ecovery/mapper/MemberMapper.java
ecovery/src/main/java/com/ecovery/service/OAuth2MemberService.java
ecovery/src/main/java/com/ecovery/service/OAuth2MemberServiceImpl.java
ecovery/src/main/resources/mapper/MemberMapper.xml

[MemberMapper] 소셜 로그인 닉네임 중복 여부 확인 메서드 추가
[MemberMapper.xml] 닉네임 중복 확인 쿼리 existsByNickname 추가
[OAuth2MemberServiceImpl] 닉네임 중복 방지 로직 추가 (nickname_provider 형태로 중복 시 숫자 suffix 증가)

[20250808] 소셜로그인 시 로그인 중복 오류 수정

---

ecovery/src/main/resources/static/css/cart-style.css
ecovery/src/main/resources/static/css/disposalMain.css
ecovery/src/main/resources/static/css/eco-market-register.css
ecovery/src/main/resources/static/css/free-sharing-register.css
ecovery/src/main/resources/static/css/header.css
ecovery/src/main/resources/static/css/mypage-style.css
ecovery/src/main/resources/templates/cart/cart.html
ecovery/src/main/resources/templates/disposal/disposalResult.html
ecovery/src/main/resources/templates/eco/eco-market-register.html
ecovery/src/main/resources/templates/fragments/header.html
ecovery/src/main/resources/templates/free/register.html
ecovery/src/main/resources/templates/mypage/home.html

분리배출 AI분석 결과 버튼 수정 완
마이페이지 ,장바구니 페이지 수정 완

분리배출 및 마이페이지 수정
